print("Hello there!")
print("Welcome To Division")
prnt("First number")
num_1 = int(input(""))
print("Second number")
num_2 = int(input(""))
Quotienn = str(num1 / num_2)
print("The quotient is " + Quotient)
