print("Hello People! ")
print("Only Division Calculator Welcomes you")
print("1st number")
num_1 = int(input(""))
print("2nd number")  
num_2 = int(input(""))
Quotient = str(num_1 / num_2)
print("The quotient is " + Quotient)
print("Nice")
