print("Hello there!")
print("Welcome To Division")
print("First number")
num_1 = int(input(""))
print("Second number")  
num_2 = int(input(""))
Quotient = str(num_1 / num_2)
print("The quotient is " + Quotient)
