print("Hello there!")
print("Welcome To Multipilcation")
print("First number")
num_1 = int(input(""))
print("Second number")
num_2 = int(input(""))
Product = str(num_1 * num_2)
print("The product is " + Product)
