print("Hello there!")
print("Welcome To Only Subtracting")
print("First number")
num_one = int(input(""))
print("Second number")
num_two = int(input(""))
Difference = str(num_one - num_two)
print("The difference is " + Difference)
