print("Hello there!")
print("Welcome To Subtraction")
print("First number")
num_1 = int(input(""))
print("Second number")
num_2 = int(input(""))
Difference = str(num_1 - num_2)
print("The difference is " + Difference)